// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpcHi.proto

package com.rivergame.protobuf.hi;

public interface HiRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HiRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
