// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpcHi.proto

package com.rivergame.protobuf.hi;

public interface HiResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HiResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
