// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpcHi.proto

package com.rivergame.protobuf.hi;

public final class WuyuGRpc {
  private WuyuGRpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HiRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HiRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HiResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HiResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013rpcHi.proto\"\031\n\tHiRequest\022\014\n\004name\030\001 \001(\t" +
      "\"\035\n\nHiResponse\022\017\n\007message\030\001 \001(\t2+\n\002Hi\022%\n" +
      "\010sayHello\022\n.HiRequest\032\013.HiResponse\"\000B\'\n\031" +
      "com.rivergame.protobuf.hiB\010WuyuGRpcP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HiRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HiRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HiRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_HiResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HiResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HiResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
